[project]
name = "ai-trip-planner"
version = "0.1.0"
description = "This is all about agent based trip planner"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.2",
]
